sudo: required
services:
  - docker

before_install:
  - docker build -t andrewpkq/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andrewpkq/react-test npm test

after_success:
  - docker build -t andrewpkq/multi-client ./client
  - docker build -t andrewpkq/multi-nginx ./nginx
  - docker build -t andrewpkq/multi-server ./server
  - docker build -t andrewpkq/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push to docker hub
  - docker push andrewpkq/multi-client
  - docker push andrewpkq/multi-nginx
  - docker push andrewpkq/multi-server
  - docker push andrewpkq/multi-worker
